-file("/usr/local/Cellar/erlang/22.0.1/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(rufus_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 79).

trim_atom(TokenChars, TokenLen) ->
    {TokenChars1, TokenLen1} = trim_leading_colon(TokenChars, TokenLen),
    case is_single_quoted(TokenChars1) of
        true ->
            list_to_atom(trim_quotes(TokenChars1, TokenLen1));
        false ->
            list_to_atom(TokenChars1)
    end.

trim_leading_colon(TokenChars, TokenLen) ->
    TrimmedTokenLen = TokenLen - 1,
    TrimmedTokenChars = lists:sublist(TokenChars, 2, TrimmedTokenLen),
    {TrimmedTokenChars, TrimmedTokenLen}.

trim_quotes(TokenChars, TokenLen) ->
    lists:sublist(TokenChars, 2, TokenLen - 2).

is_single_quoted(TokenChars) ->
    (hd(TokenChars) == $') and (lists:last(TokenChars) == $').

-file("/usr/local/Cellar/erlang/22.0.1/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.erl", 327).
yystate() -> 70.

yystate(77, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [101|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 27, Tlen);
yystate(76, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,76};
yystate(75, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,75};
yystate(74, [32|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 0, Tlen);
yystate(74, [9|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 0, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,74};
yystate(73, [101|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 27, Tlen);
yystate(73, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,73};
yystate(72, [111|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,72};
yystate(71, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(70, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line+1, Tlen+1, Action, Alen);
yystate(70, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 108 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 110, C =< 114 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [46|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,69};
yystate(68, [115|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,68};
yystate(67, [110|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, [109|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,67};
yystate(66, [10|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,66};
yystate(65, [108|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 27, Tlen);
yystate(65, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,65};
yystate(64, [110|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,64};
yystate(63, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [108|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,60};
yystate(59, [116|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,59};
yystate(58, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [117|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,57};
yystate(56, [115|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 11, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 11, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(55, Ics, Line, Tlen+1, 11, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(53, [45|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 13, Tlen);
yystate(53, [43|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 13, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 13, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,53};
yystate(52, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 8, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 8, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 8, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 8, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,52};
yystate(51, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,51};
yystate(50, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(49, [100|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,49};
yystate(48, [116|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,48};
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [114|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,46};
yystate(45, [101|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 13, Tlen);
yystate(45, [69|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 13, Tlen);
yystate(45, [45|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 13, Tlen);
yystate(45, [43|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 13, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, 13, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,45};
yystate(44, [116|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,44};
yystate(43, [112|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,43};
yystate(42, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,42};
yystate(41, [111|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,41};
yystate(40, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,40};
yystate(39, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [117|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 27, Tlen);
yystate(38, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,38};
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 13, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,37};
yystate(36, [97|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 27, Tlen);
yystate(36, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,36};
yystate(35, [111|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,35};
yystate(34, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 10, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 10, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 10, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 10, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,33};
yystate(32, [111|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,32};
yystate(31, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(30, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(28, [111|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,28};
yystate(27, [114|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 27, Tlen);
yystate(27, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,27};
yystate(26, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 12, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 12, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 12, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 12, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,26};
yystate(25, [103|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,25};
yystate(24, [111|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,24};
yystate(23, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 6, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 6, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 6, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 6, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,23};
yystate(22, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 23, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,21};
yystate(20, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,20};
yystate(19, [116|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 27, Tlen);
yystate(19, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,19};
yystate(18, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [110|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 27, Tlen);
yystate(17, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,17};
yystate(16, [108|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 27, Tlen);
yystate(16, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,16};
yystate(15, [109|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 27, Tlen);
yystate(15, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(13, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(12, [99|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, [97|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, [98|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,12};
yystate(11, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 3, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 3, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 3, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 3, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(9, [105|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,9};
yystate(8, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,8};
yystate(7, [111|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 27, Tlen);
yystate(7, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,7};
yystate(6, [116|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 27, Tlen);
yystate(6, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,6};
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,5};
yystate(4, [110|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 27, Tlen);
yystate(4, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,4};
yystate(3, [117|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [108|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [97|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 107 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 116 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(1, [114|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,1};
yystate(0, [116|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 27, Tlen);
yystate(0, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, _, _, _) ->
    yyaction_1();
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLen, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLen, TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 41).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/0}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 42).
yyaction_1() ->
     skip_token .

-compile({inline,yyaction_2/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 44).
yyaction_2(TokenLine) ->
     { token, { module, TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 45).
yyaction_3(TokenLine) ->
     { token, { import, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 46).
yyaction_4(TokenLine) ->
     { token, { const, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 47).
yyaction_5(TokenLine) ->
     { token, { func, TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 49).
yyaction_6(TokenLine) ->
     { token, { atom, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 50).
yyaction_7(TokenLine) ->
     { token, { bool, TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 51).
yyaction_8(TokenLine) ->
     { token, { float, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 52).
yyaction_9(TokenLine) ->
     { token, { int, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 53).
yyaction_10(TokenLine) ->
     { token, { string, TokenLine } } .

-compile({inline,yyaction_11/3}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 55).
yyaction_11(TokenChars, TokenLen, TokenLine) ->
     A = trim_atom (TokenChars, TokenLen),
     { token, { atom_lit, TokenLine, A } } .

-compile({inline,yyaction_12/2}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 57).
yyaction_12(TokenChars, TokenLine) ->
     { token, { bool_lit, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_13/2}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 58).
yyaction_13(TokenChars, TokenLine) ->
     { token, { float_lit, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_14/2}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 59).
yyaction_14(TokenChars, TokenLine) ->
     { token, { int_lit, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_15/3}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 60).
yyaction_15(TokenChars, TokenLen, TokenLine) ->
     S = trim_quotes (TokenChars, TokenLen),
     { token, { string_lit, TokenLine, S } } .

-compile({inline,yyaction_16/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 63).
yyaction_16(TokenLine) ->
     { token, { '(', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 64).
yyaction_17(TokenLine) ->
     { token, { ')', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 65).
yyaction_18(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 66).
yyaction_19(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 67).
yyaction_20(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 68).
yyaction_21(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 69).
yyaction_22(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 70).
yyaction_23(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 71).
yyaction_24(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 72).
yyaction_25(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 73).
yyaction_26(TokenLine) ->
     { token, { '%', TokenLine } } .

-compile({inline,yyaction_27/2}).
-file("/Users/jkakar/src/github.com/rufus-lang/rufus/rf/src/rufus_scan.xrl", 75).
yyaction_27(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-file("/usr/local/Cellar/erlang/22.0.1/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 313).
